@url = http://localhost:4000/users

GET {{url}}

###
GET {{url}}/17
###
POST {{url}}
Content-Type: application/json

{
    "Nombres": "Jorje",
    "Correo": "cmarroquin@miumg.edu.gt",
    "Contraseña": "ffsdfd",
    "Estado": "ACTIVO"
}

###
PUT {{url}}/17
Content-Type: application/json

{
    "Nombres": "ramazini",
    "Correo": "cmauin@miumg.edu.gt",
    "Contraseña": "ffd",
    "Estado": "Activo"
}

###
DELETE {{url}}/2
